# Generated by Django 5.2.4 on 2025-10-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
