# Generated by Django 5.2.4 on 2025-10-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_answer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='form_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.formcategory'),
        ),
    ]
