# Generated by Django 5.2.4 on 2025-10-09 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_question_form_category'),
        ('main', '0007_student_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.studymodule'),
        ),
    ]
