# Generated by Django 5.2.4 on 2025-10-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_useranswer_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcategory',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
