# Generated by Django 5.2.4 on 2025-10-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_formcategory_active'),
        ('main', '0008_groupmoduleteacher_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.groupmoduleteacher'),
        ),
    ]
