# Generated by Django 5.2.4 on 2025-10-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_remove_useranswer_answer_useranswer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.ManyToManyField(null=True, to='forms.answer'),
        ),
    ]
