# Generated by Django 5.2.7 on 2026-03-26 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_remove_useranswer_answer_useranswer_answer'),
        ('main', '0009_alter_groupmoduleteacher_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.telegramuser'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.groupmoduleteacher'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
