# Generated by Django 5.2.4 on 2025-10-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='telegram_user',
        ),
    ]
