# Generated by Django 5.2.4 on 2025-10-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_teacher_telegram_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymodule',
            old_name='name_ru',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='studymodule',
            name='name_uz',
        ),
    ]
