# Generated by Django 5.2.4 on 2025-10-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_ru_studymodule_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModuleTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_modules', to='main.group')),
                ('study_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_modules', to='main.studymodule')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_modules', to='main.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'study_module', 'group')},
            },
        ),
        migrations.DeleteModel(
            name='TeacherStudyModule',
        ),
    ]
