# Generated by Django 5.2.4 on 2025-10-08 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_groupmoduleteacher_delete_teacherstudymodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_users', to='main.filial'),
        ),
    ]
