# Generated by Django 5.2.4 on 2025-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_telegramuser_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
