# Generated by Django 5.2.4 on 2025-10-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmoduleteacher',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
