# Generated by Django 5.2.4 on 2025-11-04 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_groupmoduleteacher_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmoduleteacher',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_modules', to='main.group'),
        ),
        migrations.AlterField(
            model_name='groupmoduleteacher',
            name='study_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_modules', to='main.studymodule'),
        ),
    ]
